20021113

package junit.runner;

import java.io.IOException;
class A{
	public void foo() {
		try {
			System.out.println("Hello");
		} catch (IOException e) {
		}	
	}
}	

use quick fix to remove the catch block
undo - it's not undone correctly
redo - you end up in a mess
press redo/undo some more times to generate even more mess

20021113

package junit.runner;

import java.io.IOException;
class A{
	public void foo() {
		try {
			System.out.println("Hello");
		} catch (IOException e) {
		}	
	}
}	

use quick fix to remove the catch block
undo - it's not undone correctly
redo - you end up in a mess
press redo/undo some more times to generate even more mess
Fixed for M3.
