Build 20050505

I highlighted the following code and ran the "Surround With Try/Catch"
refactoring. Besides surrounding my code with the correct try/catch statement,
the refactoring reordered my lines of code (!!), introducing a compilation error.

My code before refactoring:
 DocumentBuilder builder= DocumentBuilderFactory.newInstance().newDocumentBuilder();
 builder.setErrorHandler(new DefaultHandler());
 Element root= builder.parse(configuration).getDocumentElement();

My code after the refactoring:
  Element root;
  try {
    root= builder.parse(configuration).getDocumentElement();
    DocumentBuilder builder=
DocumentBuilderFactory.newInstance().newDocumentBuilder();
    builder.setErrorHandler(new DefaultHandler());
  } catch (ParserConfigurationException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
  } catch (SAXException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
  } catch (IOException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
  }

Build 20050505

I highlighted the following code and ran the "Surround With Try/Catch"
refactoring. Besides surrounding my code with the correct try/catch statement,
the refactoring reordered my lines of code (!!), introducing a compilation error.

My code before refactoring:
 DocumentBuilder builder= DocumentBuilderFactory.newInstance().newDocumentBuilder();
 builder.setErrorHandler(new DefaultHandler());
 Element root= builder.parse(configuration).getDocumentElement();

My code after the refactoring:
  Element root;
  try {
    root= builder.parse(configuration).getDocumentElement();
    DocumentBuilder builder=
DocumentBuilderFactory.newInstance().newDocumentBuilder();
    builder.setErrorHandler(new DefaultHandler());
  } catch (ParserConfigurationException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
  } catch (SAXException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
  } catch (IOException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
  }
Fixed. Added test case TestWrappedLocal7.
