The "Surround with try/catch block" feature is very useful, but it should 
really send printStackTrace() to the caught exception.  For example, 
surrounding the following line:

    wait();

should yield:

    try {
        wait();
    } catch (InterruptedException e) {
        e.printStackTrace();
    }

When you are not sure how to handle an exception, sending printStackTrace() is 
a useful best practice.  Failing to do this causes thrown exception to be 
masked.

Another idea would be for the "Surround with try/catch block" to simply use 
the "try" template defined for the workspace.  Currently the "try" template 
does not use printStackTrace() and probably should.

The "Surround with try/catch block" feature is very useful, but it should 
really send printStackTrace() to the caught exception.  For example, 
surrounding the following line:

    wait();

should yield:

    try {
        wait();
    } catch (InterruptedException e) {
        e.printStackTrace();
    }

When you are not sure how to handle an exception, sending printStackTrace() is 
a useful best practice.  Failing to do this causes thrown exception to be 
masked.

Another idea would be for the "Surround with try/catch block" to simply use 
the "try" template defined for the workspace.  Currently the "try" template 
does not use printStackTrace() and probably should.
This is now customizable using the new code templates


"Surround with try/catch block" should use printStackTrace()

